/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.co.aosd.bifunction;

import java.util.function.BiFunction;

/**
 * Utility functions to combing BiFunctions for use with an environment parameter.
 *
 * @author Tony Walmsley, AOSD Ltd.
 */
public interface ComposableBiFunction<ENV, T, R> extends BiFunction<ENV, T, R> {

    /**
     * Combines two ComposableBiFunction by treating the first parameter to both functions as an `environment` that
     * needs to be available to both ComposableBiFunction. The return type of the first BiFunction must match the
     * second parameter type of the second ComposableBiFunction.
     *
     * @param first a ComposableBiFunction - executed before this
     * @return a combination of the two ComposableBiFunction that implements `this(env, first(env, p1))`
     */
    default <U> ComposableBiFunction<ENV, U, R> biCombine(final ComposableBiFunction<ENV, U, T> first) {
        return (e, t) -> this.apply(e, first.apply(e, t));
    }

    /**
     * Combines two ComposableBiFunction by treating the first parameter to both functions as an `environment` that
     * needs to be available to both ComposableBiFunction. The return type of the first ComposableBiFunction must
     * match the second parameter type of the second ComposableBiFunction.
     *
     * @param second a ComposableBiFunction - executed after this
     * @return a combination of the two ComposableBiFunction that implements `second(env, this(env, p1))`
     */
    default <U> ComposableBiFunction<ENV, T, U> biAndThen(final ComposableBiFunction<ENV, R, U> second) {
        return (e, t) -> second.apply(e, this.apply(e, t));
    }

}
